// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  AddressControllerCreateData,
  AddressControllerCreateResponses,
  AddressControllerFindAllData,
  AddressControllerFindAllResponses,
  AddressControllerFindOneData,
  AddressControllerFindOneResponses,
  AddressControllerRemoveData,
  AddressControllerRemoveResponses,
  AddressControllerUpdateData,
  AddressControllerUpdateResponses,
  AppControllerGetHelloData,
  AppControllerGetHelloResponses,
  AppControllerHealth0Data,
  AppControllerHealth0Responses,
  AppControllerHealth1Data,
  AppControllerHealth1Responses,
  AppControllerVersionData,
  AppControllerVersionResponses,
  AuthControllerDecodeData,
  AuthControllerDecodeResponses,
  AuthControllerGetTokenForOtherUserData,
  AuthControllerGetTokenForOtherUserResponses,
  AuthControllerLoginData,
  AuthControllerLoginErrors,
  AuthControllerLoginResponses,
  AuthControllerRefreshTokenData,
  AuthControllerRefreshTokenErrors,
  AuthControllerRefreshTokenResponses,
  AuthControllerResendInviteMailData,
  AuthControllerResendInviteMailResponses,
  AuthControllerResetPasswordData,
  AuthControllerResetPasswordResponses,
  AuthControllerSetPasswordData,
  AuthControllerSetPasswordErrors,
  AuthControllerTestApiKeyData,
  AuthControllerTestApiKeyResponses,
  AuthControllerValidateHashData,
  AuthControllerValidateHashErrors,
  CustomersControllerCreateData,
  CustomersControllerCreateResponses,
  CustomersControllerFindAllData,
  CustomersControllerFindAllResponses,
  CustomersControllerFindOneData,
  CustomersControllerFindOneResponses,
  CustomersControllerRemoveData,
  CustomersControllerRemoveResponses,
  CustomersControllerUpdateData,
  CustomersControllerUpdateResponses,
  DeviceTokenControllerCreateData,
  DeviceTokenControllerCreateResponses,
  DeviceTokenControllerFindAllData,
  DeviceTokenControllerFindAllResponses,
  DeviceTokenControllerFindOneData,
  DeviceTokenControllerFindOneResponses,
  DeviceTokenControllerRemoveAllData,
  DeviceTokenControllerRemoveAllResponses,
  DeviceTokenControllerSendNotificationData,
  DeviceTokenControllerSendNotificationResponses,
  DeviceTokenControllerUpdateData,
  DeviceTokenControllerUpdateResponses,
  LanguageControllerGetAllData,
  LanguageControllerGetAllResponses,
  PermissionControllerGetAllData,
  PermissionControllerGetAllResponses,
  RoleControllerCreateData,
  RoleControllerCreateErrors,
  RoleControllerFindAllData,
  RoleControllerFindAllResponses,
  RoleControllerFindOneData,
  RoleControllerFindOneResponses,
  RoleControllerRemoveData,
  RoleControllerRemoveErrors,
  RoleControllerUpdateData,
  RoleControllerUpdateErrors,
  TenantControllerCreateData,
  TenantControllerCreateErrors,
  TenantControllerFindAllData,
  TenantControllerFindAllResponses,
  TenantControllerFindOneData,
  TenantControllerFindOneResponses,
  TenantControllerRemoveData,
  TenantControllerRemoveResponses,
  TenantControllerUpdateData,
  TenantControllerUpdateErrors,
  TenantKpiControllerCountActiveUsersData,
  TenantKpiControllerCountActiveUsersErrors,
  TenantKpiControllerUsersCountByCreatedMonthData,
  TenantKpiControllerUsersCountByCreatedMonthErrors,
  TenantKpiControllerUsersCountByCreatedMonthResponses,
  UserControllerCreateData,
  UserControllerCreateErrors,
  UserControllerFindAllData,
  UserControllerFindAllResponses,
  UserControllerFindOneData,
  UserControllerFindOneResponses,
  UserControllerRemoveData,
  UserControllerRemoveErrors,
  UserControllerUpdateData,
  UserControllerUpdateErrors,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const appControllerGetHello = <ThrowOnError extends boolean = false>(
  options?: Options<AppControllerGetHelloData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AppControllerGetHelloResponses,
    unknown,
    ThrowOnError
  >({ url: '/', ...options });

export const appControllerHealth0 = <ThrowOnError extends boolean = false>(
  options?: Options<AppControllerHealth0Data, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AppControllerHealth0Responses,
    unknown,
    ThrowOnError
  >({ url: '/health', ...options });

export const appControllerHealth1 = <ThrowOnError extends boolean = false>(
  options?: Options<AppControllerHealth1Data, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AppControllerHealth1Responses,
    unknown,
    ThrowOnError
  >({ url: '/undefined/health', ...options });

export const appControllerVersion = <ThrowOnError extends boolean = false>(
  options?: Options<AppControllerVersionData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AppControllerVersionResponses,
    unknown,
    ThrowOnError
  >({ url: '/version', ...options });

/**
 * Restricted to permissions: USER_READ, USER_READ_OWN
 */
export const userControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<UserControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    UserControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user',
    ...options,
  });

/**
 * Restricted to permissions: USER_CREATE
 */
export const userControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    unknown,
    UserControllerCreateErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Restricted to permissions: USER_DELETE, USER_DELETE_OWN
 */
export const userControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    unknown,
    UserControllerRemoveErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user/{id}',
    ...options,
  });

/**
 * Restricted to permissions: USER_READ, USER_READ_OWN
 */
export const userControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    UserControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user/{id}',
    ...options,
  });

/**
 * Restricted to permissions: USER_UPDATE, USER_UPDATE_OWN
 */
export const userControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    unknown,
    UserControllerUpdateErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const authControllerLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerLoginData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AuthControllerLoginResponses,
    AuthControllerLoginErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const authControllerRefreshToken = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthControllerRefreshTokenData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AuthControllerRefreshTokenResponses,
    AuthControllerRefreshTokenErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/refreshToken',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const authControllerDecode = <ThrowOnError extends boolean = false>(
  options?: Options<AuthControllerDecodeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AuthControllerDecodeResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/decode',
    ...options,
  });

/**
 * Restricted to permissions: USER_CREATE
 */
export const authControllerResendInviteMail = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthControllerResendInviteMailData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AuthControllerResendInviteMailResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/resendInviteMail',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const authControllerResetPassword = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthControllerResetPasswordData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AuthControllerResetPasswordResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/resetPassword',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const authControllerValidateHash = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthControllerValidateHashData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    unknown,
    AuthControllerValidateHashErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/validate/{hash}',
    ...options,
  });

export const authControllerSetPassword = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerSetPasswordData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    unknown,
    AuthControllerSetPasswordErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/setPassword/{hash}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const authControllerTestApiKey = <ThrowOnError extends boolean = false>(
  options?: Options<AuthControllerTestApiKeyData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AuthControllerTestApiKeyResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ name: 'apikey', type: 'apiKey' }],
    url: '/auth/test/apikey',
    ...options,
  });

/**
 * Restricted to permissions: SUPER_ADMIN
 */
export const authControllerGetTokenForOtherUser = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthControllerGetTokenForOtherUserData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    AuthControllerGetTokenForOtherUserResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/tokenForOtherUser/{userId}',
    ...options,
  });

/**
 * Restricted to permissions: ROLE_READ, ROLE_READ_OWN
 */
export const roleControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<RoleControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    RoleControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/role',
    ...options,
  });

/**
 * Restricted to permissions: ROLE_CREATE
 */
export const roleControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<RoleControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    unknown,
    RoleControllerCreateErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/role',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Restricted to permissions: ROLE_DELETE
 */
export const roleControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<RoleControllerRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    unknown,
    RoleControllerRemoveErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/role/{id}',
    ...options,
  });

/**
 * Restricted to permissions: ROLE_READ, ROLE_READ_OWN
 */
export const roleControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<RoleControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    RoleControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/role/{id}',
    ...options,
  });

/**
 * Restricted to permissions: ROLE_UPDATE
 */
export const roleControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<RoleControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    unknown,
    RoleControllerUpdateErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/role/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Restricted to permissions: TENANT_READ, TENANT_READ_OWN
 */
export const tenantControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<TenantControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    TenantControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tenant',
    ...options,
  });

/**
 * Restricted to permissions: GLOBAL_USER, TENANT_CREATE
 */
export const tenantControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<TenantControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    unknown,
    TenantControllerCreateErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tenant',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Restricted to permissions: GLOBAL_USER, TENANT_DELETE, TENANT_DELETE_OWN
 */
export const tenantControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<TenantControllerRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    TenantControllerRemoveResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tenant/{id}',
    ...options,
  });

/**
 * Restricted to permissions: TENANT_READ, TENANT_READ_OWN
 */
export const tenantControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<TenantControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    TenantControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tenant/{id}',
    ...options,
  });

/**
 * Restricted to permissions: GLOBAL_USER, TENANT_UPDATE, TENANT_UPDATE_OWN
 */
export const tenantControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<TenantControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    unknown,
    TenantControllerUpdateErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tenant/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const customersControllerFindAll = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<CustomersControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    CustomersControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/customers',
    ...options,
  });

export const customersControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<CustomersControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CustomersControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/customers',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const customersControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<CustomersControllerRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    CustomersControllerRemoveResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/customers/{id}',
    ...options,
  });

export const customersControllerFindOne = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CustomersControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CustomersControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/customers/{id}',
    ...options,
  });

export const customersControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<CustomersControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    CustomersControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/customers/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const permissionControllerGetAll = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PermissionControllerGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    PermissionControllerGetAllResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/permission',
    ...options,
  });

export const deviceTokenControllerFindAll = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeviceTokenControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    DeviceTokenControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/device-token',
    ...options,
  });

export const deviceTokenControllerCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeviceTokenControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    DeviceTokenControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/device-token',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const deviceTokenControllerFindOne = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeviceTokenControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    DeviceTokenControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/device-token/{id}',
    ...options,
  });

export const deviceTokenControllerUpdate = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeviceTokenControllerUpdateData, ThrowOnError>,
) =>
  (options?.client ?? client).patch<
    DeviceTokenControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/device-token/{id}',
    ...options,
  });

/**
 * Restricted to permissions: SUPER_ADMIN
 */
export const deviceTokenControllerSendNotification = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeviceTokenControllerSendNotificationData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    DeviceTokenControllerSendNotificationResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/device-token/Notification/{id}',
    ...options,
  });

export const deviceTokenControllerRemoveAll = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeviceTokenControllerRemoveAllData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    DeviceTokenControllerRemoveAllResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/device-token/{deviceToken}',
    ...options,
  });

export const languageControllerGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<LanguageControllerGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    LanguageControllerGetAllResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/language',
    ...options,
  });

/**
 * Restricted to permissions:
 */
export const addressControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<AddressControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AddressControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/address',
    ...options,
  });

/**
 * Restricted to permissions:
 */
export const addressControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<AddressControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AddressControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/address',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Restricted to permissions: USER_DELETE, USER_DELETE_OWN
 */
export const addressControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<AddressControllerRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    AddressControllerRemoveResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/address/{id}',
    ...options,
  });

/**
 * Restricted to permissions:
 */
export const addressControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<AddressControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    AddressControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/address/{id}',
    ...options,
  });

/**
 * Restricted to permissions:
 */
export const addressControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<AddressControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    AddressControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/address/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Restricted to permissions: KPI_TENANT
 */
export const tenantKpiControllerCountActiveUsers = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<TenantKpiControllerCountActiveUsersData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    unknown,
    TenantKpiControllerCountActiveUsersErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/kpi/tenant/activeUsers',
    ...options,
  });

/**
 * Restricted to permissions: KPI_TENANT
 */
export const tenantKpiControllerUsersCountByCreatedMonth = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    TenantKpiControllerUsersCountByCreatedMonthData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    TenantKpiControllerUsersCountByCreatedMonthResponses,
    TenantKpiControllerUsersCountByCreatedMonthErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/kpi/tenant/usersCountByCreatedMonth',
    ...options,
  });
