// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string;
};

export type UserDto = {
  tenantId?: string;
  email: string;
  password: string | null;
  firstName: string;
  lastName: string;
  phone: string;
  active: boolean;
  roleId: string;
};

export type User = {
  id: string;
  createdAt: string;
  updatedAt: string;
  tenantId: string | null;
  email: string;
  firstName: string;
  lastName: string;
  phone: string;
  active: boolean;
  inviteAcceptedAt: string | null;
  language: 'de' | 'en';
  roleId: string | null;
};

export type UserFindAllResponseDto = {
  total: number;
  records: Array<User>;
};

export type LoginBody = {
  username: string;
  password: string;
};

export type AuthResponse = {
  user: User;
  access_token: string;
  refresh_token: string;
};

export type RefreshBody = {
  refreshToken: string;
};

export type ResendInviteBody = {
  userId: string;
};

export type ResetPwBody = {
  email: string;
};

export type SetPwBody = {
  password: string;
};

export type RoleDto = {
  tenantId?: string;
  name: string;
  description: string;
  /**
   * A global role could only be assigned to users with `tenant = null`
   */
  global: boolean;
  /**
   * If a role is a draft, `global` is always `true`.A draft role also could not be applied to users.
   */
  draft: boolean;
  superAdmin: boolean;
  tenantAdmin: boolean;
  permissions: Array<
    | 'FILE_READ'
    | 'FILE_READ_OWN'
    | 'FILE_CREATE'
    | 'FILE_UPDATE'
    | 'FILE_UPDATE_OWN'
    | 'FILE_DELETE'
    | 'FILE_DELETE_OWN'
    | 'ROLE_READ'
    | 'ROLE_READ_OWN'
    | 'ROLE_CREATE'
    | 'ROLE_UPDATE'
    | 'ROLE_DELETE'
    | 'TENANT_READ'
    | 'TENANT_READ_OWN'
    | 'TENANT_CREATE'
    | 'TENANT_UPDATE'
    | 'TENANT_UPDATE_OWN'
    | 'TENANT_DELETE'
    | 'TENANT_DELETE_OWN'
    | 'USER_READ'
    | 'USER_READ_OWN'
    | 'USER_CREATE'
    | 'USER_UPDATE'
    | 'USER_UPDATE_OWN'
    | 'USER_DELETE'
    | 'USER_DELETE_OWN'
    | 'KPI_TENANT'
  >;
};

export type Role = {
  id: string;
  createdAt: string;
  updatedAt: string;
  tenantId: string | null;
  name: string;
  description: string;
  superAdmin: boolean;
  tenantAdmin: boolean;
  global: boolean;
  draft: boolean;
  permissions: Array<
    | 'FILE_READ'
    | 'FILE_READ_OWN'
    | 'FILE_CREATE'
    | 'FILE_UPDATE'
    | 'FILE_UPDATE_OWN'
    | 'FILE_DELETE'
    | 'FILE_DELETE_OWN'
    | 'ROLE_READ'
    | 'ROLE_READ_OWN'
    | 'ROLE_CREATE'
    | 'ROLE_UPDATE'
    | 'ROLE_DELETE'
    | 'TENANT_READ'
    | 'TENANT_READ_OWN'
    | 'TENANT_CREATE'
    | 'TENANT_UPDATE'
    | 'TENANT_UPDATE_OWN'
    | 'TENANT_DELETE'
    | 'TENANT_DELETE_OWN'
    | 'USER_READ'
    | 'USER_READ_OWN'
    | 'USER_CREATE'
    | 'USER_UPDATE'
    | 'USER_UPDATE_OWN'
    | 'USER_DELETE'
    | 'USER_DELETE_OWN'
    | 'KPI_TENANT'
  >;
};

export type RoleFindAllResponseDto = {
  total: number;
  records: Array<Role>;
};

export type TenantDto = {
  name: string;
};

export type Tenant = {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
};

export type TenantFindAllResponseDto = {
  total: number;
  records: Array<Tenant>;
};

export type CreateCustomerDto = {
  tenantId?: string;
  name: string;
};

export type Customer = {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
};

export type CustomerFindAllResponseDto = {
  total: number;
  records: Array<Customer>;
};

export type UpdateCustomerDto = {
  [key: string]: unknown;
};

export type DeleteResultDto = {
  /**
   * Number of affected rows
   */
  affected: number;
};

export type DeviceTokenDto = {
  tenantId?: string;
  deviceToken: string;
};

export type DeviceToken = {
  id: string;
  createdAt: string;
  updatedAt: string;
  tenantId: string;
  userId: string;
  deviceToken: string;
};

export type DeviceTokenFindAllResponseDto = {
  total: number;
  records: Array<DeviceToken>;
};

export type NotificationResponseDto = {
  /**
   * Whether the notification was sent successfully
   */
  success: boolean;
};

export type AddressDto = {
  tenantId?: string;
  street: string;
  houseNo: string;
  postalCode: string;
  city: string;
  longitude: number;
  latitude: number;
};

export type Address = {
  id: string;
  createdAt: string;
  updatedAt: string;
  tenantId: string;
  street: string | null;
  houseNo: string | null;
  postalCode: string | null;
  city: string | null;
  longitude: number;
  latitude: number;
};

export type AddressFindAllResponseDto = {
  total: number;
  records: Array<Address>;
};

export type AppControllerGetHelloData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/';
};

export type AppControllerGetHelloResponses = {
  200: unknown;
};

export type AppControllerHealth0Data = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type AppControllerHealth0Responses = {
  200: unknown;
};

export type AppControllerHealth1Data = {
  body?: never;
  path?: never;
  query?: never;
  url: '/undefined/health';
};

export type AppControllerHealth1Responses = {
  200: unknown;
};

export type AppControllerVersionData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/version';
};

export type AppControllerVersionResponses = {
  200: unknown;
};

export type UserControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter users based on their active status
     */
    active?: boolean;
    /**
     * Number of records to skip
     */
    skip?: number;
    /**
     * Limit on the number of records to return
     */
    limit?: number;
    /**
     * Search value
     */
    search?: string;
    /**
     * SearchDate value
     */
    searchDate?: string;
  };
  url: '/user';
};

export type UserControllerFindAllResponses = {
  default: UserFindAllResponseDto;
};

export type UserControllerFindAllResponse = UserControllerFindAllResponses[keyof UserControllerFindAllResponses];

export type UserControllerCreateData = {
  body: UserDto;
  path?: never;
  query?: never;
  url: '/user';
};

export type UserControllerCreateErrors = {
  /**
   * RELATION_PERMISSION: Requesting user does not have permission to related record. e.g. a tenant admin tries to create a global user.
   */
  406: unknown;
  /**
   * OBSOLETE_TENANT: This user cannot have a tenant
   */
  409: unknown;
};

export type UserControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/user/{id}';
};

export type UserControllerRemoveErrors = {
  /**
   * LAST_SUPER_ADMIN: Last user of super admin role can not be deleted
   */
  409: unknown;
};

export type UserControllerFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/user/{id}';
};

export type UserControllerFindOneResponses = {
  default: User;
};

export type UserControllerFindOneResponse = UserControllerFindOneResponses[keyof UserControllerFindOneResponses];

export type UserControllerUpdateData = {
  body: UserDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/user/{id}';
};

export type UserControllerUpdateErrors = {
  /**
   * ADMIN_EMAIL: The email of the superAdmin is not updatable
   */
  409: unknown;
};

export type AuthControllerLoginData = {
  body: LoginBody;
  path?: never;
  query?: never;
  url: '/auth/login';
};

export type AuthControllerLoginErrors = {
  /**
   * UNAUTHORIZED: Wrong Credentials
   */
  401: unknown;
};

export type AuthControllerLoginResponses = {
  201: AuthResponse;
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerRefreshTokenData = {
  body: RefreshBody;
  path?: never;
  query?: never;
  url: '/auth/refreshToken';
};

export type AuthControllerRefreshTokenErrors = {
  /**
   * User not found
   */
  404: unknown;
  /**
   * RefreshToken expired
   */
  417: unknown;
};

export type AuthControllerRefreshTokenResponses = {
  201: AuthResponse;
};

export type AuthControllerRefreshTokenResponse =
  AuthControllerRefreshTokenResponses[keyof AuthControllerRefreshTokenResponses];

export type AuthControllerDecodeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/decode';
};

export type AuthControllerDecodeResponses = {
  200: unknown;
};

export type AuthControllerResendInviteMailData = {
  body: ResendInviteBody;
  path?: never;
  query?: never;
  url: '/auth/resendInviteMail';
};

export type AuthControllerResendInviteMailResponses = {
  201: unknown;
};

export type AuthControllerResetPasswordData = {
  body: ResetPwBody;
  path?: never;
  query?: never;
  url: '/auth/resetPassword';
};

export type AuthControllerResetPasswordResponses = {
  201: unknown;
};

export type AuthControllerValidateHashData = {
  body?: never;
  path: {
    hash: string;
  };
  query?: never;
  url: '/auth/validate/{hash}';
};

export type AuthControllerValidateHashErrors = {
  /**
   * HASH_INVALID: Hash is not valid
   */
  400: unknown;
};

export type AuthControllerSetPasswordData = {
  body: SetPwBody;
  path: {
    hash: string;
  };
  query?: never;
  url: '/auth/setPassword/{hash}';
};

export type AuthControllerSetPasswordErrors = {
  /**
   * HASH_INVALID: Hash is not valid
   */
  400: unknown;
};

export type AuthControllerTestApiKeyData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/test/apikey';
};

export type AuthControllerTestApiKeyResponses = {
  200: unknown;
};

export type AuthControllerGetTokenForOtherUserData = {
  body?: never;
  path: {
    userId: string;
  };
  query?: never;
  url: '/auth/tokenForOtherUser/{userId}';
};

export type AuthControllerGetTokenForOtherUserResponses = {
  200: unknown;
};

export type RoleControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    tenantId?: string;
    draft?: boolean;
    global?: boolean;
    superAdmin?: boolean;
    name?: string;
    sort?: string;
    limit?: number;
    skip?: number;
  };
  url: '/role';
};

export type RoleControllerFindAllResponses = {
  default: RoleFindAllResponseDto;
};

export type RoleControllerFindAllResponse = RoleControllerFindAllResponses[keyof RoleControllerFindAllResponses];

export type RoleControllerCreateData = {
  body: RoleDto;
  path?: never;
  query?: never;
  url: '/role';
};

export type RoleControllerCreateErrors = {
  /**
   * BAD_REQUEST: Wrong parameters. Can not do that
   */
  400: unknown;
  /**
   * NOT_ENOUGH_POWER: You are not allowed to create such a role
   */
  403: unknown;
  /**
   * NO_GLOBAL_PERMISSION: You are not permitted to create a global role
   */
  405: unknown;
  /**
   * DRAFT_HAS_BE_GLOBAL: A draft Role has to be global!
   */
  406: unknown;
  /**
   * UNIQUE: There is already a role with this name and tenant
   */
  409: unknown;
  /**
   * TENANT_ADMIN_EXISTS: There is already a tenant admin role
   */
  422: unknown;
};

export type RoleControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/role/{id}';
};

export type RoleControllerRemoveErrors = {
  /**
   * HAS_USERS: This role has users, so it can not be deleted
   */
  409: unknown;
  /**
   * TENANT_ADMIN: Tenant Admin role can not be removed
   */
  422: unknown;
};

export type RoleControllerFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/role/{id}';
};

export type RoleControllerFindOneResponses = {
  default: Role;
};

export type RoleControllerFindOneResponse = RoleControllerFindOneResponses[keyof RoleControllerFindOneResponses];

export type RoleControllerUpdateData = {
  body: RoleDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/role/{id}';
};

export type RoleControllerUpdateErrors = {
  /**
   * UNIQUE: There is already a role with this name and tenant
   */
  409: unknown;
};

export type TenantControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    search?: string;
    name?: string;
    sort?: string;
    limit?: number;
    skip?: number;
  };
  url: '/tenant';
};

export type TenantControllerFindAllResponses = {
  default: TenantFindAllResponseDto;
};

export type TenantControllerFindAllResponse = TenantControllerFindAllResponses[keyof TenantControllerFindAllResponses];

export type TenantControllerCreateData = {
  body: TenantDto;
  path?: never;
  query?: never;
  url: '/tenant';
};

export type TenantControllerCreateErrors = {
  /**
   * UNIQUE: There is already a tenant with this name
   */
  409: unknown;
};

export type TenantControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/tenant/{id}';
};

export type TenantControllerRemoveResponses = {
  200: unknown;
};

export type TenantControllerFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/tenant/{id}';
};

export type TenantControllerFindOneResponses = {
  default: Tenant;
};

export type TenantControllerFindOneResponse = TenantControllerFindOneResponses[keyof TenantControllerFindOneResponses];

export type TenantControllerUpdateData = {
  body: TenantDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/tenant/{id}';
};

export type TenantControllerUpdateErrors = {
  /**
   * UNIQUE: There is already a tenant with this name
   */
  409: unknown;
};

export type CustomersControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    searchDate?: string;
    search?: string;
    sort?: string;
    limit?: number;
    skip?: number;
  };
  url: '/customers';
};

export type CustomersControllerFindAllResponses = {
  default: CustomerFindAllResponseDto;
};

export type CustomersControllerFindAllResponse =
  CustomersControllerFindAllResponses[keyof CustomersControllerFindAllResponses];

export type CustomersControllerCreateData = {
  body: CreateCustomerDto;
  path?: never;
  query?: never;
  url: '/customers';
};

export type CustomersControllerCreateResponses = {
  default: Customer;
};

export type CustomersControllerCreateResponse =
  CustomersControllerCreateResponses[keyof CustomersControllerCreateResponses];

export type CustomersControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/customers/{id}';
};

export type CustomersControllerRemoveResponses = {
  default: DeleteResultDto;
};

export type CustomersControllerRemoveResponse =
  CustomersControllerRemoveResponses[keyof CustomersControllerRemoveResponses];

export type CustomersControllerFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/customers/{id}';
};

export type CustomersControllerFindOneResponses = {
  default: Customer;
};

export type CustomersControllerFindOneResponse =
  CustomersControllerFindOneResponses[keyof CustomersControllerFindOneResponses];

export type CustomersControllerUpdateData = {
  body: UpdateCustomerDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/customers/{id}';
};

export type CustomersControllerUpdateResponses = {
  default: Customer;
};

export type CustomersControllerUpdateResponse =
  CustomersControllerUpdateResponses[keyof CustomersControllerUpdateResponses];

export type PermissionControllerGetAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/permission';
};

export type PermissionControllerGetAllResponses = {
  200: unknown;
};

export type DeviceTokenControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    name?: string;
    sort?: string;
    limit?: number;
    skip?: number;
  };
  url: '/device-token';
};

export type DeviceTokenControllerFindAllResponses = {
  default: DeviceTokenFindAllResponseDto;
};

export type DeviceTokenControllerFindAllResponse =
  DeviceTokenControllerFindAllResponses[keyof DeviceTokenControllerFindAllResponses];

export type DeviceTokenControllerCreateData = {
  body: DeviceTokenDto;
  path?: never;
  query?: never;
  url: '/device-token';
};

export type DeviceTokenControllerCreateResponses = {
  201: unknown;
};

export type DeviceTokenControllerFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/device-token/{id}';
};

export type DeviceTokenControllerFindOneResponses = {
  default: DeviceToken;
};

export type DeviceTokenControllerFindOneResponse =
  DeviceTokenControllerFindOneResponses[keyof DeviceTokenControllerFindOneResponses];

export type DeviceTokenControllerUpdateData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/device-token/{id}';
};

export type DeviceTokenControllerUpdateResponses = {
  200: unknown;
};

export type DeviceTokenControllerSendNotificationData = {
  body?: never;
  path?: never;
  query: {
    token: string;
    title: string;
    body: string;
  };
  url: '/device-token/Notification/{id}';
};

export type DeviceTokenControllerSendNotificationResponses = {
  default: NotificationResponseDto;
};

export type DeviceTokenControllerSendNotificationResponse =
  DeviceTokenControllerSendNotificationResponses[keyof DeviceTokenControllerSendNotificationResponses];

export type DeviceTokenControllerRemoveAllData = {
  body?: never;
  path?: never;
  query?: {
    deviceToken?: string;
  };
  url: '/device-token/{deviceToken}';
};

export type DeviceTokenControllerRemoveAllResponses = {
  200: unknown;
};

export type LanguageControllerGetAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/language';
};

export type LanguageControllerGetAllResponses = {
  200: unknown;
};

export type AddressControllerFindAllData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    skip?: number;
  };
  url: '/address';
};

export type AddressControllerFindAllResponses = {
  default: AddressFindAllResponseDto;
};

export type AddressControllerFindAllResponse =
  AddressControllerFindAllResponses[keyof AddressControllerFindAllResponses];

export type AddressControllerCreateData = {
  body: AddressDto;
  path?: never;
  query?: never;
  url: '/address';
};

export type AddressControllerCreateResponses = {
  201: unknown;
};

export type AddressControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/address/{id}';
};

export type AddressControllerRemoveResponses = {
  200: unknown;
};

export type AddressControllerFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/address/{id}';
};

export type AddressControllerFindOneResponses = {
  default: Address;
};

export type AddressControllerFindOneResponse =
  AddressControllerFindOneResponses[keyof AddressControllerFindOneResponses];

export type AddressControllerUpdateData = {
  body: AddressDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/address/{id}';
};

export type AddressControllerUpdateResponses = {
  200: unknown;
};

export type TenantKpiControllerCountActiveUsersData = {
  body?: never;
  path?: never;
  query?: {
    tenantId?: string;
  };
  url: '/kpi/tenant/activeUsers';
};

export type TenantKpiControllerCountActiveUsersErrors = {
  /**
   * MISSING_TENANT: Please specify a tenant
   */
  409: unknown;
};

export type TenantKpiControllerUsersCountByCreatedMonthData = {
  body?: never;
  path?: never;
  query?: {
    tenantId?: string;
  };
  url: '/kpi/tenant/usersCountByCreatedMonth';
};

export type TenantKpiControllerUsersCountByCreatedMonthErrors = {
  /**
   * MISSING_TENANT: Please specify a tenant
   */
  409: unknown;
};

export type TenantKpiControllerUsersCountByCreatedMonthResponses = {
  /**
   * Users count by created month. January is 01, December is 12.
   */
  200: unknown;
};
